import { Helmet } from 'react-helmet-async'
import { Link } from 'react-router-dom'

function GEM() {

  return (
    <>
      <Helmet>
        <title>Gilt-Edged Mini</title>
        <meta name='description' content='A simple description of the Gilt-Edged Mini project' />
      </Helmet>    
      <div className="container">
        <h1 className="mt-4" id="market-finance">
          Gilt-Edged Mini
        </h1>

        <h2 className='mb-4 mt-4'>
          GEM Intention
        </h2>

        <p>
          GEM offers a particular context for thinking about the long-term bonds issued by the United Kingdom of Great Britain and Northern Ireland (UK) government. From the <Link className="icon-link" to="/reading" id="crashed">reading</Link>, fascinating stories elucidate the coercive power relationships fundamental to both the design and operation of a state monetary system. Descriptions of political-economy - of institutions and their history - stand alongside fully articulated accounting logic that clearly sets out how money is created, distributed and destroyed. GEM is the incremental development of <span className="fw-bold">highly simplified</span> computational (agent-based) models of the English money system that has been in place since the <button type="button" className="btn btn-link ps-0 pe-0 icon-link" data-bs-toggle="modal" data-bs-target="#modernTurn" style={{ marginTop: `-9px`, marginBottom: `-5px` }}>modern turn</button>.
        </p>

        <h2 className='mb-4 mt-4'>
          Models
        </h2>

        <p>
          <Link className="icon-link" to="/reading#monetary-economics" id="monetary-economics">Monetary Economics</Link> is a book written by Wynne Godley and Marc Lavoie (G&amp;L). G&amp;L's book informs, but may not be the only source, of accounting logic at the heart of all model developments. The number of agent-based models (ABMs) developed include, but are not limited to, simple (ABMSIM), portfolio choice (ABMPC) and liquidity preference (ABMLP). Agent-Based Model Liquidity Preference-X (ABMLP-X) is the latest model development.
        </p>

        <h3 className='mb-3 mt-4'>
          Structure
        </h3>

        <p>
          Broadly, models are structured with class agents categorised as: <span className="fst-italic">Rule makers</span>, typically the government and the central bank, and <span className="fst-italic">rule takers</span>, at minimum, these are producers and households who behave accordingly. Models may consume real-world economic time-series data (see the <a className="icon-link" href="https://www.ons.gov.uk" target="_blank">ONS <i className="bi bi-box-arrow-up-right mb-2"></i></a> website). Model <a className="icon-link" href="https://gist.githubusercontent.com/danodriscoll/19a3c5817871a34fb68cef1e59000c82/raw/f854e02573662aefae6ee5e20e03d30460a2649a/model_params.txt" target="_blank">parameters <i className="bi bi-box-arrow-up-right mb-2"></i></a> (rules) include, but are not limited to, government <span className="fst-italic">expenditure</span><sup>1</sup>, <span className="fst-italic">taxation</span> and <span className="fst-italic">interest</span> (base) rate time-series data.
        </p>

        <h3 className='mb-3 mt-4'>
          Speculating On a Gilt-Edged Past, Present and Future
        </h3>

        <p>
          Moving away from the steady state by way of events<sup>2</sup>, rules and agent behaviours:
        </p>        

        <ul className="list-group list-group-flush mb-4">
          <li className="list-group-item">Annual economic time-series data exploded into quarterly financial time-series: From the beginning of 1850 to the end of 1954.</li>
          <li className="list-group-item">Quarterly economic time-series <a className="icon-link" href="https://www.data-reports.net/giltedged-info/explode_quarterly_values.html" target="_blank">exploded <i className="bi bi-box-arrow-up-right mb-2"></i></a> into monthly financial time-series: From the beginning of 1955 to the latest release of economic time-series data.</li>
        </ul>

        <p>
          <span className="fw-bold">ONS data consumption</span>: The behavioural-logic desires of <span className="fst-italic">rule takers</span> are always recorded. However, while the decision-making logic of household agents can affect their personal circumstance, the collective decisions of either producers or households will not directly affect the key <span className="fst-italic">model run</span> parameters set by <span className="fst-italic">rule makers</span>.
        </p>

        <p>
          <span className="fw-bold">Beyond latest ONS data</span>: A model scenario may proceed with parameters generated by model logics alone. ONS time-series data is typically one financial quarter behind today's date. A model run determined by model agent logics is an imagined, speculative scenario - a journey to both present and future. In these scenarios, the mutable fiscal and monetary parameters set by <span className="fst-italic">rule makers</span> may become increasingly shaped by the behavioural desires of <span className="fst-italic">rule takers</span> - households of a certain profile - reflecting new forms of feedback within a speculative model run.
        </p>

        <h3 className='mb-3 mt-4'>
          Model Scenario Outputs
        </h3>

        <p>
          As models evolve, the number and type of model scenario outputs will grow. Outputs are wrangled in a Jupyter notebook environment. Blending wrangled scenario output with real-word economic data will require flexibility of analysis and presentation.
        </p>

        <p>
          View the <a className="icon-link" href="https://www.giltedged.systems" target="_self">GiltEdged.systems <i className="bi bi-box-arrow-up-right mb-2"></i></a> website for agent-model descriptions as well as simple interactive data applications. <span className="text-muted">Email:</span> <a className="icon-link" href="mailto:daniel@giltedged.info">daniel@giltedged.info</a>.
        </p>

        <div className="text-success">
          <hr className="mt-4 mb-4 col-md-6" />
        </div>

        <ul className="list-unstyled">
          <li>
            <sup>1</sup><small> UK expenditure time-series may be divided as such: The ONS UK <a className="icon-link" href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/timeseries/ukpop/pop" target="_blank">population <i className="bi bi-box-arrow-up-right mb-2"></i></a> estimate by the total number of model household agents.</small>
          </li>
          <li>
            <sup>2</sup><small> Real-World financial crises, wars and pandemic(s).</small>
          </li>
        </ul>


        <div className="modal fade" id="modernTurn" tabIndex="-1" aria-labelledby="modernTurnLabel" aria-hidden="true">
          <div className="modal-dialog modal-lg">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title" id="modernTurnLabel">Modern Turn</h5>
                <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div className="modal-body">
                <p>
                  When the visibility of money as a political project faded, the way it had realigned the societies that authored it also disappeared from view. With that disappearance went compelling questions about the consequences of the transformation - including the role of fiscal action in supporting the value of money<sup>1</sup>.
                </p>
                <p>
                Reconsidering its creation story suggests that <span className="fst-italic">making money</span> is a constitutional project. In mediaeval England, silver and gold were only the beginning, not the end, of the story. They furnished the material value upon which the mediaeval world would act out a debate over how to package, pay and circulate value. That effort distributed resources. It shaped nation building. It configured new ways to represent counted value - public debt, circulating credit, and elaborate hierarchies of credit are all part of the story, as are markets, banks, securities and financial crises. The way the English made money shaped and reshaped the way people conceptualised it and the way they conducted monetary policy. As a matter engineered on a fiscal frame, enhanced by the unique cash quality it offered, and expanded for a charge, money has never been neutral<sup>2</sup>.
                </p>
                <p>
                Bank (of England) notes, like bills, had been blessed from the beginning, or very close to it, by a second constitutional contrivance. Both public officials and individual holders cooperated to institutionalise them as a mode of payment by giving them a unique stature in exchange between the government and its citizens. ... The stature of the Bank's notes again set them apart from their competitors. Specie was not actually <span className="fst-italic">backing</span> Bank issues in the sense that redemption was a significant part of the functioning system. According to the numbers in circulation, people held Bank notes rather than demanding specie. ... Freed from more laborious work, specie began assuming its modern role. First, it acted, as a kind of security, a default guarantee. If the Bank notes failed as money, people could claim specie as a back-up. Less directly, but more practically, specie was a legitimating device. The Bank's commitment to cash its demand instruments visibly limited the number it could issue. And the image offered of gold or silver in the vault gave those holding paper the sense that an anchor existed - even if the anchor was actually elsewhere, in the sound functioning of the fiscal system<sup>3</sup>.
                </p>
                <ul className="list-unstyled">
                  <li>
                    <sup>1</sup><small> Desan, <span className="fst-italic">Making Money</span>, p. 22</small>
                  </li>
                  <li>
                    <sup>2</sup> <small>p. 69</small>
                  </li>
                  <li>
                    <sup>3</sup> <small>pp. 311-319</small>
                  </li>
                </ul>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

      </div>

    </>
  )
}

export default GEM
